const fs=require('node:fs'),path=require('node:path');
const Runtime=require('../web/src/positioning/runtime'),Nav=require('../web/src/positioning/navigation');
const maps=require('../web/data/navigation/areas-v1.json'),displayMap=require('../web/data/maps/floor-04.json'),allModels=require('../web/data/positioning/motion-models.json');
const manifest=require('../data/manifest.json'),root=path.resolve(__dirname,'../..'),map=Nav.compile(maps,4);
const names=new Set(manifest.sessions.filter(s=>s.route_id==='4F_CORE_TO_RIGHT_STAIRS'||s.route_id==='4F_CORE_TO_LEFT_STAIRS').map(s=>s.file));
const median=a=>{const b=[...a].sort((x,y)=>x-y);return b.length?b[Math.floor(b.length/2)]:null;};
const mean=a=>a.length?a.reduce((s,x)=>s+x,0)/a.length:null,metric=x=>Nav.metricDistance(map,x);
function truth(label){if(label.includes('오른쪽 계단'))return map.distanceMetric.mapBreaks[0];if(label.includes('왼쪽 계단'))return 135.407;const id=label.match(/42\d\d/)?.[0],room=displayMap.rooms.find(r=>r.id===id);return room?.front_x??room?.x;}
function yaw(v){const [x,y,z,w0]=v,w=Number.isFinite(w0)?w0:Math.sqrt(Math.max(0,1-x*x-y*y-z*z));return (Math.atan2(2*(w*z+x*y),1-2*(y*y+z*z))*180/Math.PI+360)%360;}
function replay(file,enabled){const rows=fs.readFileSync(file,'utf8').trim().split(/\r?\n/).map(JSON.parse),first=rows[0],right=first.label.route_id.includes('RIGHT');
 const models={...allModels,templates:allModels.templates.filter(t=>t.source!==path.basename(file))};
 const r=Runtime.create(maps,models,[],{floor:4,x:70.804,y:0,platform:'android',device:first.device||first.device_model,initialDirectionSign:right?-1:1,magneticZoneEnabled:false,sequenceEnabled:enabled,bleEnabled:false});
 const laps=[];for(const row of rows){const t=row.wall_time_ms;if(row.sensor==='rotation_vector')Runtime.heading(r,t,yaw(row.values),3);if(row.sensor==='accelerometer_mps2')Runtime.acceleration(r,t,row.values);if(row.sensor==='magnetic_field_ut')Runtime.magnetic(r,t,row.values);if(row.kind==='label'){const x=truth(row.label.location);if(Number.isFinite(x)){const s=Runtime.snapshot(r,[]);laps.push({label:row.label.location,errorMeters:Math.abs(metric(s.x)-metric(x))});}}}
 const s=Runtime.snapshot(r,[]);return {maeMeters:mean(laps.map(x=>x.errorMeters)),endpointErrorMeters:laps.at(-1)?.errorMeters??null,sequence:s.sequenceStats,laps};}
const results=[];for(const name of names){const file=path.join(root,'indoor/data',manifest.raw_directory,name);if(!fs.existsSync(file))continue;results.push({file:name,pdr:replay(file,false),magV2:replay(file,true)});}
const report={createdAt:new Date().toISOString(),method:'Android 4F route leave-one-session-out replay. Scalar magnetic zone is disabled. V2 uses disjoint 8-step windows, direction/device matching, soft weighting, and a 12 m PDR gate.',results,summary:{sessions:results.length,pdrMAE:mean(results.map(r=>r.pdr.maeMeters)),magV2MAE:mean(results.map(r=>r.magV2.maeMeters)),pdrEndpoint:mean(results.map(r=>r.pdr.endpointErrorMeters)),magV2Endpoint:mean(results.map(r=>r.magV2.endpointErrorMeters)),evaluated:results.reduce((s,r)=>s+r.magV2.sequence.evaluated,0),applied:results.reduce((s,r)=>s+r.magV2.sequence.applied,0)},limitations:['Only two right-direction sessions and one left-direction session exist. Left has no independent same-device reference.','Lap positions are map-derived weak labels.','No BLE exists in these historical moving logs.']};
const out=path.join(root,'indoor/data/analysis/detailed-20260918/4f-magnetic-ablation/android-mag-v2-replay.json');fs.writeFileSync(out,JSON.stringify(report,null,2)+'\n');console.log(JSON.stringify({...report,results:results.map(r=>({file:r.file,pdr:r.pdr.maeMeters,magV2:r.magV2.maeMeters,sequence:r.magV2.sequence}))},null,2));
