const fs=require('node:fs'),path=require('node:path');
const Z=require('../web/src/positioning/zone-classifier');
const root=path.resolve(__dirname,'../..'),input=process.argv[2]?path.resolve(process.argv[2]):path.join(root,'indoor/data/raw/android/2026-09-19/kakao-pull');
const out=process.argv[3]?path.resolve(process.argv[3]):path.join(root,'indoor/data/analysis/detailed-20260919/android-radio/route-ble-windows.json');
const median=a=>{const b=[...a].sort((x,y)=>x-y),n=b.length;return n%2?b[(n-1)/2]:(b[n/2-1]+b[n/2])/2;};
const fp=(rows,min=2)=>{const g=new Map();for(const r of rows){if(!r.anonymous_id||!Number.isFinite(r.rssi_dbm))continue;if(!g.has(r.anonymous_id))g.set(r.anonymous_id,[]);g.get(r.anonymous_id).push(r.rssi_dbm);}return Object.fromEntries([...g].filter(([,v])=>v.length>=min).map(([k,v])=>[k,median(v)]));};
const files=fs.readdirSync(input).filter(f=>f.endsWith('.jsonl')).map(file=>{const rows=fs.readFileSync(path.join(input,file),'utf8').trim().split(/\r?\n/).map(JSON.parse);return {file,rows,start:rows[0]};});
const anchors=files.filter(s=>s.start.label?.zone_id).map(s=>({floor:Number(s.start.label.floor),platform:'android',device:s.start.device,zone:s.start.label.zone_id,label:s.start.label.location,ble:fp(s.rows.filter(r=>r.kind==='ble_observation'),3)}));
const routes=files.filter(s=>!s.start.label?.zone_id).map(s=>{const ble=s.rows.filter(r=>r.kind==='ble_observation'),start=s.start.wall_time_ms,end=s.rows.findLast(r=>r.kind==='session_end')?.wall_time_ms||ble.at(-1)?.wall_time_ms,windows=[];
 for(let t=start;t<end;t+=5000){const rssi=fp(ble.filter(r=>r.wall_time_ms>=t&&r.wall_time_ms<t+5000));if(Object.keys(rssi).length<5){windows.push({second:Math.round((t-start)/1000),reason:'insufficient_signals',signals:Object.keys(rssi).length});continue;}const now=t+5000,o=Z.classify({id:`${s.file}-${t}`,timestamp:now,platform:'android',device:s.start.device,floors:[Number(s.start.label.floor)],ble:{supported:true,timestamp:now,rssi}},anchors,now),top=o.candidates[0],second=o.candidates[1],context=ble.find(r=>r.wall_time_ms>=t&&r.wall_time_ms<t+5000)?.route_context;windows.push({second:Math.round((t-start)/1000),lap:context?.last_lap_index,at:context?.last_lap_location,signals:Object.keys(rssi).length,predicted:top?.zone||null,weight:top?.weight||null,margin:top&&second?top.weight-second.weight:top?.weight||null,secondZone:second?.zone||null,reason:o.reason});}
 const counts={};for(const w of windows)if(w.predicted)counts[w.predicted]=(counts[w.predicted]||0)+1;return {file:s.file,route:s.start.label.route_id,durationSeconds:(end-start)/1000,windows,counts};});
const report={createdAt:new Date().toISOString(),method:'Disjoint 5 s moving BLE windows classified against the later stationary anchors from the same day/device.',anchors:anchors.map(a=>({zone:a.zone,signals:Object.keys(a.ble).length})),routes,limitation:'A moving window is labelled only by the most recently pressed lap, so this is a temporal plausibility check, not coordinate accuracy. Same-day references are not an independent test.'};fs.writeFileSync(out,JSON.stringify(report,null,2)+'\n');console.log(JSON.stringify(routes.map(r=>({file:r.file,route:r.route,windows:r.windows.length,counts:r.counts,timeline:r.windows.map(w=>`${w.second}s:${w.predicted||w.reason}`)})),null,2));
